# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='nome',
            new_name='name',
        ),
        migrations.AddField(
            model_name='projects',
            name='filedata',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
