# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171228_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='cloud_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='creation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
